name: liquid_glass_bottom_nav

description: >
  A customizable floating liquid-glass bottom navigation bar for Flutter
  with smooth animated destinations, multiple navigation styles,
  and an independent action button.

version: 0.1.0-dev.1

homepage: https://github.com/sharon505/liquid_glass_bottom_nav
repository: https://github.com/sharon505/liquid_glass_bottom_nav
issue_tracker: https://github.com/sharon505/liquid_glass_bottom_nav/issues

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.9.3
  liquid_glass_renderer: ^0.2.0-dev.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true